config/routes.rb
Vet::Application.routes.draw do
  resources :problemas

  resources :animalitos do
    member do
      get 'show1'
    end
  end

  resources :categorias

end

app/models/animalito.rb
class Animalito < ActiveRecord::Base
  attr_accessible :name, :categoria_id, :born_on, :female, :problema_ids
  belongs_to :categoria
  has_many :sintomas
  has_many :problemas, :through => :sintomas
  validates_presence_of :name, :born_on
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nombre, :descripcion
  has_many :animalitos
  validates_presence_of :nombre
  def to_s
    nombre
    #[nombre, descripcion].join(", ") #en este ejemplo concatenamos dos campos para mostrar en el combobox
  end
end

app/models/problema.rb
class Problema < ActiveRecord::Base
  attr_accessible :nombre
  has_many :sintomas
  has_many :animalitos, :through => :sintomas
  def to_s
    nombre
  end
end

app/models/sintoma.rb
class Sintoma < ActiveRecord::Base
  attr_accessible :animalito_id, :problema_id
  belongs_to :animalito
  belongs_to :problema
end

app/controllers/animalitos_controller.rb
class AnimalitosController < ApplicationController
  def index
    @animalitos = Animalito.all
  end

  def show
    @animalito = Animalito.find(params[:id])
  end

  def show1
    @animalito = Animalito.find(params[:id])
  end

  def new
    @animalito = Animalito.new
  end

  def create
    @animalito = Animalito.new(params[:animalito])
    if @animalito.save
      redirect_to @animalito, :notice => "Successfully created animalito."
    else
      render :action => 'new'
    end
  end

  def edit
    @animalito = Animalito.find(params[:id])
  end

  def update
    @animalito = Animalito.find(params[:id])
    if @animalito.update_attributes(params[:animalito])
      redirect_to @animalito, :notice  => "Successfully updated animalito."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @animalito = Animalito.find(params[:id])
    @animalito.destroy
    redirect_to animalitos_url, :notice => "Successfully destroyed animalito."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  def index
    @categorias = Categoria.all
  end

  def show
    @categoria = Categoria.find(params[:id])
  end

  def new
    @categoria = Categoria.new
  end

  def create
    @categoria = Categoria.new(params[:categoria])
    if @categoria.save
      redirect_to @categoria, :notice => "Successfully created categoria."
    else
      render :action => 'new'
    end
  end

  def edit
    @categoria = Categoria.find(params[:id])
  end

  def update
    @categoria = Categoria.find(params[:id])
    if @categoria.update_attributes(params[:categoria])
      redirect_to @categoria, :notice  => "Successfully updated categoria."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy
    redirect_to categorias_url, :notice => "Successfully destroyed categoria."
  end
end

app/controllers/problemas_controller.rb
class ProblemasController < ApplicationController
  def index
    @problemas = Problema.all
  end

  def show
    @problema = Problema.find(params[:id])
  end

  def new
    @problema = Problema.new
  end

  def create
    @problema = Problema.new(params[:problema])
    if @problema.save
      redirect_to @problema, :notice => "Successfully created problema."
    else
      render :action => 'new'
    end
  end

  def edit
    @problema = Problema.find(params[:id])
  end

  def update
    @problema = Problema.find(params[:id])
    if @problema.update_attributes(params[:problema])
      redirect_to @problema, :notice  => "Successfully updated problema."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @problema = Problema.find(params[:id])
    @problema.destroy
    redirect_to problemas_url, :notice => "Successfully destroyed problema."
  end
end

app/helpers/animalitos_helper.rb
module AnimalitosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/problemas_helper.rb
module ProblemasHelper
end

app/views/animalitos/_form.html.haml
= semantic_form_for @animalito do |f|
  = f.error_messages
  = f.inputs do
    = f.input :name, :hint => "Entre el nombre del propietario sino se proporciona"
    = f.input :born_on, :start_year => 1950
    = f.input :categoria, :include_blank => false
    = f.input :female, :as => :radio, :label => "Genero", :collection => [["Male", false], ["Female", true]]
    = f.input :problemas, :as => :check_boxes
    =f.buttons

app/views/animalitos/edit.html.haml
- title "Edit Animalito"

= render 'form'

%p
  = link_to "Show", @animalito
  |
  = link_to "View All", animalitos_path

app/views/animalitos/index.html.haml
- title "Animalitos"

%table
  %tr
    %th Name
    %th Categoria
    %th Born on
    %th Female
  - for animalito in @animalitos
    %tr
      %td= animalito.name
      %td= animalito.categoria_id
      %td= animalito.born_on
      %td= animalito.female
      %td= link_to 'Show', animalito
      %td= link_to 'Edit', edit_animalito_path(animalito)
      %td= link_to 'Destroy', animalito, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Animalito", new_animalito_path

app/views/animalitos/new.html.haml
- title "New Animalito"

= render 'form'

%p= link_to "Back to List", animalitos_path

app/views/animalitos/show.html.haml
= show_for @animalito do |a|
  = a.attributes :name, :categoria_id, :born_on, :female, :problemas
  = link_to "Edit", edit_animalito_path(@animalito)
  |
  = link_to "Destroy", @animalito, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", animalitos_path

app/views/animalitos/show1.html.haml
- title "Animalito"

%p
  %strong Name:
  = @animalito.name
%p
  %strong Categoria:
  = @animalito.categoria_id
%p
  %strong Born On:
  = @animalito.born_on
%p
  %strong Female:
  = @animalito.female
%p
  %strong Problemas:
  = @animalito.problemas.map{|a| a.nombre}.join(", ")
%p
  = link_to "Edit", edit_animalito_path(@animalito)
  |
  = link_to "Destroy", @animalito, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", animalitos_path

app/views/categorias/_form.html.erb
<%= semantic_form_for @categoria do |f| %>
  <%= f.inputs %>
  <%= f.buttons %>
<% end %>

app/views/categorias/edit.html.erb
<% title "Edit Categoria" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @categoria %> |
  <%= link_to "View All", categorias_path %>
</p>

app/views/categorias/index.html.erb
<% title "Categorias" %>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
  </tr>
  <% for categoria in @categorias %>
    <tr>
      <td><%= categoria.nombre %></td>
      <td><%= categoria.descripcion %></td>
      <td><%= link_to "Show", categoria %></td>
      <td><%= link_to "Edit", edit_categoria_path(categoria) %></td>
      <td><%= link_to "Destroy", categoria, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Categoria", new_categoria_path %></p>

app/views/categorias/new.html.erb
<% title "New Categoria" %>

<%= render 'form' %>

<p><%= link_to "Back to List", categorias_path %></p>

app/views/categorias/show.html.erb
<% title "Categoria" %>

<p>
  <strong>Nombre:</strong>
  <%= @categoria.nombre %>
</p>
<p>
  <strong>Descripcion:</strong>
  <%= @categoria.descripcion %>
</p>

<p>
  <%= link_to "Edit", edit_categoria_path(@categoria) %> |
  <%= link_to "Destroy", @categoria, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", categorias_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="es">
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag 'application', 'formtastic', 'formtastic_changes', :cache => 'base' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/problemas/_form.html.erb
<%= form_for @problema do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/problemas/edit.html.erb
<% title "Edit Problema" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @problema %> |
  <%= link_to "View All", problemas_path %>
</p>

app/views/problemas/index.html.erb
<% title "Problemas" %>

<table>
  <tr>
    <th>Nombre</th>
  </tr>
  <% for problema in @problemas %>
    <tr>
      <td><%= problema.nombre %></td>
      <td><%= link_to "Show", problema %></td>
      <td><%= link_to "Edit", edit_problema_path(problema) %></td>
      <td><%= link_to "Destroy", problema, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Problema", new_problema_path %></p>

app/views/problemas/new.html.erb
<% title "New Problema" %>

<%= render 'form' %>

<p><%= link_to "Back to List", problemas_path %></p>

app/views/problemas/show.html.erb
<% title "Problema" %>

<p>
  <strong>Nombre:</strong>
  <%= @problema.nombre %>
</p>

<p>
  <%= link_to "Edit", edit_problema_path(@problema) %> |
  <%= link_to "Destroy", @problema, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", problemas_path %>
</p>